#--------------------------------------
# sect: META
#--------------------------------------
meta:
  #engine: 4.0.4
  version: 0.1
  author: JackMatanky
  name: snak
  ref: &kb_ref "SNAK v0.1"
  full_name: &kb_full_name "SNAK: Sisyphus Needed a Keyboard, v0.1"
  url: &kb_url https://github.com/JackMatanky/kb_snak
  # switch:
  #   $extends: presets.mx
  #   $extends: presets.choc_v1
  #   $extends: presets.choc_v2

#--------------------------------------
# sect: UNITS
#--------------------------------------
units:
  # Key Size (Choc V1)
  # Space Between Key Centers
  kx: cx # 18
  ky: cy # 17
  kxo: 0.5(kx)
  kyo: 0.5(ky)
  # Column Spread and Row Padding
  spread_key: 18.5
  padding_key: 17.5
  # Keycap Size
  keycap_x: 17.5
  keycap_y: 16.5
  # Switch Plate Key Cutout
  kcutout_x: 13.9
  kcutout_y: 13.9

  # Padding Variables
  px: kx + 4
  py: ky + 4
  pxo: 0.5(px)
  pyo: 0.5(py)

  # Double Padding Variables
  dpx: kx + 8
  dpy: ky + 8

  # Column Stagger
  stagger_ring: 2(kx)/3
  stagger_middle: (kx)/3
  stagger_index: -(kx)/3
  stagger_inner: -(kx)/6
  stagger_thumb: -(kx)/8

  # Thumb
  offset_thumb_x: 11
  offset_thumb_y: -25.25
  splay_thumb_out: -15
  splay_thumb_in: -10
  spread_thumb_in: 4(kx)/3

  # nice!nano: 34.1 x 18.3 x 3.3 (mm)
  # The nice nano footprint's center doesn't account
  mcu_size_x: 18.3
  mcu_size_y: 34.1
  mcu_size_xo: 0.5(mcu_size_x)
  mcu_size_yo: 0.5(mcu_size_y)
  mcu_spacing_left: 1.5
  mcu_spacing_right: 1
  mcu_shift_x: kxo + mcu_size_xo + mcu_spacing_left
  mcu_shift_y: kyo - mcu_size_yo - 0.35
  mcu_right_board_shift_x: mcu_size_xo + mcu_spacing_right
  mcu_top_left_board_shift_x: mcu_spacing_left - mcu_size_xo - 1
  mcu_top_board_shift_y: mcu_size_yo + 0.5
  mcu_bottom_board_shift_y: -(mcu_size_yo)

  # nice!view: 36 x 14 x 2.9 (mm)
  oled_size_x: 14
  oled_size_y: 36
  oled_size_xo: 0.5(oled_size_x)
  oled_size_yo: 0.5(oled_size_y)
  oled_shift_x: 0
  oled_shift_y: mcu_size_yo - oled_size_yo - 0.5
  oled_jumper_y: 2.6
  # Screen Size and Offset From Center
  oled_screen_offset_x: 1.6
  oled_screen_offset_top_y: 2.45 + 3.65
  oled_screen_offset_bot_y: 1.3 + 1.7 + 1.6
  oled_screen_size_x: oled_size_x - 2(oled_screen_offset_x)
  oled_screen_size_y: oled_size_y - (oled_screen_offset_top_y + oled_screen_offset_bot_y)
  oled_screen_shift_x: 0
  oled_screen_shift_y: -(oled_screen_offset_top_y - oled_screen_offset_bot_y)


  # Reset Switch
  sw_reset_size_x: 3.4 # Footprint; Actual width: 2.9
  sw_reset_size_y: 5.5 # Footprint; Actual height: 4.7
  sw_reset_size_xo: 0.5(sw_reset_size_x)
  sw_reset_size_yo: 0.5(sw_reset_size_y)
  sw_reset_shift_x: -4.25
  sw_reset_shift_y: 13.25
  sw_reset_rotate: 75

  # Power Switch
  sw_power_size_x: 4.55 # Footprint; Actual width: 3.0 ± 0.05
  sw_power_size_y: 8.8 # Footprint; Actual height: 8.3
  sw_power_size_xo: 0.5(sw_power_size_x)
  sw_power_size_yo: 0.5(sw_power_size_y)
  sw_power_shift_x: -1
  sw_power_shift_y: 15
  sw_power_rotate: 123

  # JST Battery Connector (2P, Curved Needed)
  jst_size_x: 6.9 # Footprint; Actual width: 4.5 ± 0.2
  jst_size_y: 10.35 # Footprint; Actual height: 6.1 ± 0.1
  # Footprint center at (3.45, 1.85)
  jst_size_xo: 0.5(jst_size_x)
  jst_size_yo: 0.5(jst_size_y)
  jst_shift_x: oled_size_xo
  jst_shift_y:  -(oled_size_yo + oled_jumper_y + jst_size_xo)
  jst_rotate: 270

  # PCB and Case Holes
  # Points height and width
  hole_size_x: 0.1
  hole_size_y: 0.1
  # Screw and Standoff Radii
  screw: 1
  standoff: 1.5
  # Positions
  hole_right_shift_x: 9
  hole_right_shift_y: -6.25
  hole_left_shift_x: 9
  hole_left_shift_y: 7.5
  hole_thumb_shift_x: 12
  hole_thumb_shift_y: 0

  # Outline Shapes
  board_fillet: 3
  round_board_fillet: 3.25

  # Top Border
  top_rect_size_x: 5(kx) + 0.54(pxo)
  top_rect_size_y: 2px
  top_rect_shift_x: 0
  top_rect_shift_y: 0
  
  # Top Right Circle
  top_right_crcl_radius: 125
  top_right_crcl_shift_x: -1.561
  top_right_crcl_shift_y: -96.4

  # Top Left Circle
  top_left_crcl_radius: 100
  top_left_crcl_shift_x: 15
  top_left_crcl_shift_y: -68

  # Bottom Curve
  bot_rect_size_x: 5(px)
  bot_rect_size_y: 2(px)
  bot_rect_shift_x: 10
  bot_rect_shift_y: -60

  bot_circle_radius: 235
  bot_circle_shift_x: -11.5
  bot_circle_shift_y: -246.2

#--------------------------------------
# sect: POINTS
#--------------------------------------
# columns nets up
points:
  zones:

    # * Base Keyboard Layout 
    matrix:
      # Position in center of KiCAD workspace.
      anchor:
        shift: [100, -100]
      key:
        padding: padding_key
        spread: spread_key
        tags: key
      rows:
        bot.row_net: R2
        mid.row_net: R3
        top.row_net: R4
      columns:
        pinky.key:
          column_net: C1
        ring.key:
          stagger: stagger_ring
          column_net: C2
        middle.key:
          stagger: stagger_middle
          column_net: C3
        index.key:
          stagger: stagger_index
          column_net: C4
        inner.key:
          stagger: stagger_inner
          column_net: C5
    thumb:
      key.tags: key
      anchor:
        ref: matrix_index_bot
        shift: [offset_thumb_x, offset_thumb_y]
      rows.home.row_net: R1
      columns:
        # Pinky side
        out.key:
          name: thumb_out
          splay: splay_thumb_out
          column_net: T1
        # Inner side
        in.key:
          name: thumb_in
          stagger: stagger_thumb
          spread: spread_thumb_in
          splay: splay_thumb_in
          column_net: T2
    
    # * Components
    mcu:
      key:
        tags: part
        name: mcu
        width: mcu_size_x
        height: mcu_size_y
      anchor:
        ref: matrix_inner_top
        shift: [mcu_shift_x, mcu_shift_y - kyo]
    oled:
      key:
        tags: part
        name: oled
        width: oled_size_x
        height: oled_size_y
      anchor:
        ref: mcu
        shift: [oled_shift_x, oled_shift_y]
    oled_screen:
      key:
        tags: part
        name: oled_screen
        width: oled_screen_size_x
        height: oled_screen_size_y
      anchor:
        ref: mcu
        shift: [oled_shift_x, oled_shift_y]
    sw_reset:
      key:
        tags: part
        name: sw_reset
        width: sw_reset_size_x
        height: sw_reset_size_y
      anchor:
        ref: matrix_inner_top
        shift: [sw_reset_shift_x, sw_reset_shift_y]
        rotate: sw_reset_rotate
    sw_power:
      key:
        tags: part
        name: sw_power
        width: sw_power_size_x
        height: sw_power_size_y
      anchor:
        ref: matrix_pinky_top
        shift: [sw_power_shift_x, sw_power_shift_y]
        rotate: sw_power_rotate
    jst:
      key:
        tags: part
        name: jst
        width: jst_size_x
        height: jst_size_y
      anchor:
        ref: oled
        shift: [jst_shift_x, jst_shift_y]
        rotate: jst_rotate
    
    # * Mounting Holes
    hole_left_top:
      key:
        tags: hole
        width: hole_size_x
        height: hole_size_y
      anchor:
        ref: matrix_pinky_top
        shift: [hole_left_shift_x, hole_left_shift_y]
    hole_left_bot:
      key:
        tags: hole
        width: hole_size_x
        height: hole_size_y
      anchor:
        ref: matrix_pinky_bot
        shift: [hole_left_shift_x, hole_left_shift_y]
    hole_right_top:
      key:
        tags: hole
        width: hole_size_x
        height: hole_size_y
      anchor:
        ref: matrix_index_top
        shift: [hole_right_shift_x, hole_right_shift_y]
    hole_right_bot:
      key:
        tags: hole
        width: hole_size_x
        height: hole_size_y
      anchor:
        ref: matrix_index_bot
        shift: [hole_right_shift_x, hole_right_shift_y]
    hole_btwn_thumb:
      key:
        tags: hole
        width: hole_size_x
        height: hole_size_y
      anchor:
        ref: thumb_out
        shift: [hole_thumb_shift_x, hole_thumb_shift_y]

#--------------------------------------
# sect: OUTLINES
#--------------------------------------
outlines:
  # BOARD COMPONENTS
  _raw:
    - what: rectangle
      where: [key]
      bound: true
      size: [px, py]
  _keycaps:
  # Key outline minus .5mm to show overlapping keys.
    - what: rectangle
      where: [key]
      bound: false
      size: [keycap_x, keycap_y]
  _switches:
    - what: rectangle
      where: [key]
      bound: false
      size: [kcutout_x, kcutout_y]
  
  _mcu:
    - what: rectangle
      size: [mcu_size_x, mcu_size_y]
      adjust:
        ref: mcu
  _oled:
    - what: rectangle
      size: [oled_size_x, oled_size_y]
      adjust:
        ref: oled
  _sw_reset:
    - what: rectangle
      size: [sw_reset_size_x, sw_reset_size_y]
      adjust:
        ref: sw_reset
  _sw_power:
    - what: rectangle
      size: [sw_power_size_x, sw_power_size_y]
      adjust:
        ref: sw_power
  _jst:
    - what: rectangle
      size: [jst_size_x, jst_size_y]
      adjust:
        ref: jst
  _holes_screw:
    - what: circle
      where: [hole]
      radius: screw
  _holes_standoff:
    - what: circle
      where: [hole]
      radius: standoff

  # SHAPES
  _board:
    - what: polygon
      fillet: board_fillet
      points:
        # Pinky
        - ref: matrix_pinky_bot
          shift: [-pxo, -pyo]
        - ref: matrix_pinky_top
          shift: [-pxo, .5kyo]
        # Ring
        - ref: matrix_ring_top
          shift: [-kxo, kyo]
        # Middle
        - ref: matrix_middle_top
          shift: [-kxo, kyo]
        - ref: matrix_middle_top
          shift: [kxo, kyo]
        # Inner
        - ref: matrix_inner_top
          shift: [pxo, kyo]
        # MCU
        - ref: mcu # MCU Top Left Corner
          shift: [mcu_top_left_board_shift_x, mcu_top_board_shift_y]
        - ref: mcu # MCU Top Right Corner
          shift: [mcu_right_board_shift_x, mcu_top_board_shift_y]
        - ref: mcu # MCU Bottom Right Corner
          shift: [mcu_right_board_shift_x, mcu_bottom_board_shift_y]
        # Thumb
        # MCU-thumb curve
        - ref: thumb_in
          shift: [pxo, pyo]
        - ref: thumb_in
          shift: [pxo, -pyo]

  # Top Border
  # Right Side
  _top_rect:
    - what: rectangle
      size: [top_rect_size_x, top_rect_size_y]
      adjust:
        ref: matrix_middle_top
        shift: [top_rect_shift_x, top_rect_shift_y]
  _top_right:
    - name: _top_rect
    - what: circle
      radius: top_right_crcl_radius
      adjust:
        ref: matrix_middle_mid
        shift: [top_right_crcl_shift_x, top_right_crcl_shift_y]
      operation: intersect
  _top_left:
    - name: _top_rect
    - what: circle
      radius: top_left_crcl_radius
      adjust:
        ref: matrix_middle_mid
        shift: [top_left_crcl_shift_x, top_left_crcl_shift_y]
      operation: intersect
  _top_curve:
    - name: _top_left
    - name: _top_right
      operation: intersect
  
  # Bottom Border
  _bot_rect:
    - what: rectangle
      size: [bot_rect_size_x, bot_rect_size_y]
      adjust:
        ref: matrix_middle_mid
        shift: [bot_rect_shift_x, bot_rect_shift_y]
  _bot_curve:
    - name: _bot_rect
    - what: circle
      radius: bot_circle_radius
      adjust:
        ref: matrix_pinky_bot
        shift: [bot_circle_shift_x, bot_circle_shift_y]
      operation: intersect

  # DXF PREVIEWS
  # Pure key outline with nice!nano MCU
  _raw_keys:
    - name: _raw
    - operation: stack
      name: _keycaps
  _components:
    - name: _mcu
      operation: stack
    - name: _oled
      operation: stack
    - name: _sw_reset
      operation: stack
    - name: _sw_power
      operation: stack
    - name: _jst
      operation: stack

  top_plate:
    - name: _switches
    - operation: add
      name: _holes_screw
  bottom_plate:
    - name: _holes_standoff
  board_keys:
    - name: _board
    - operation: subtract
      name: _keycaps
  board_raw_keys:
    - name: _board
    - operation: subtract
      name: _raw_keys
  round_board:
    - name: _board
    - operation: add
      name: _top_curve
    - operation: subtract
      name: _bot_curve
      fillet: round_board_fillet
  round_board_keys:
    - name: round_board
    - operation: subtract
      name: _keycaps
  round_board_mcu_keys:
    - name: round_board_keys
    - operation: subtract
      name: _mcu
  round_board_full:
    - name: round_board_keys
    - operation: stack
      name: _components
  round_board_raw_keys:
    - name: round_board
    - operation: subtract
      name: _raw_keys

#--------------------------------------
# sect: PCB
#--------------------------------------
pcbs:
  snak:
    outlines:
      main.outline: round_board
      plate_top:
        outline: top_plate
        layer: Eco1.User
      plate_bottom:
        outline: bottom_plate
        layer: Eco2.User
    footprints:
      # Key Switches and Diodes
      choc:
        what: choc_kim
        where: [key]
        params:
          reverse: true
          hotswap: true
          solder: false
          show_keycaps: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode_kim
        where: [key]
        params:
          include_tht: true
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust.shift: [0, -5]
      via_column_net:
        what: via
        where: [key]
        params.net: "{{column_net}}"
        adjust.shift: [3.75, -2.5]
      via_col_row:
        what: via
        where: [key]
        params.net: "{{colrow}}"
        adjust.shift: [-3.25, -0.5]

      # MCU
      nice_nano:
        what: nice_nano_pretty
        where.ref: mcu
        params:
          traces: true
          show_via_labels: true
          show_silk_labels: true
          show_instructions: true

          # Pin Assignments (Controller on top facing down)
          # Right Side
          P0: "F1" # Column Ring
          P1: "F2" # Column Pinky
          # GND
          # GND
          P2: "F3" # Column Middle
          P3: "F4" # Column Index
          P4: "DPD" # MOSI: Display Data
          P5: "DPC" # SCK: Display Clock
          P6: "DPE" # Display CS (nice!view only)
          P7: "R1" # Row Thumb
          P8: "T1" # Thumb Outer
          P9: "T2" # Thumb Inner

          # Left Side
          # RAW       # Battery Pos
          # GND       # Ground / Battery Neg
          # RST       # Reset pin
          # VCC       # External Power
          P21: "C1" # Column Pinky
          P20: "C2" # Column Ring
          P19: "C3" # Column Middle
          P18: "C4" # Column Index
          P15: "C5" # Column Inner
          P14: "R4" # Row Top
          P16: "R3" # Row Middle
          P10: "R2" # Row Bottom
      # OLED
      nice_view:
        what: nice_view
        where.ref: oled
        params:
          reverse: true
          MOSI: DPD
          SCK: DPC
          CS: DPE
          show_labels: true
          jumpers_at_bottom: true
      via_oled_mosi: # Via for SCK Back
        what: via
        where:
          ref: oled
          shift: [-oled_size_xo - 2.5, -oled_size_yo - 2.0]
        params.net: DPD
      via_oled_sck: # Via for SCK Back
        what: via
        where:
          ref: oled
          shift: [-oled_size_xo - 1.25, -oled_size_yo - 1.25]
        params.net: DPC
      via_oled_cs: # Via for CS Back
        what: via
        where:
          ref: oled
          shift: [-oled_size_xo, -oled_size_yo - 0.5]
        params.net: DPE

      # Reset Button
      reset:
        what: switch_reset
        where.ref: sw_reset
        params:
          reverse: true
          from: GND
          to: RST
      via_reset_rst: # left side of pwr switch
        what: via
        where:
          ref: sw_reset
          shift: [-0.5(sw_reset_size_xo), -(sw_reset_size_yo) - 1]
        params.net: RST
      via_reset_gnd: # right side of pwr switch
        what: via
        where:
          ref: sw_reset
          shift: [-(sw_reset_size_xo), -(sw_reset_size_yo) - 1]
        params.net: GND

      # Power Switch
      power:
        what: switch_power
        where.ref: sw_power
        params:
          reverse: true
          from: pos
          to: RAW
      via_raw: # right side of pwr switch
        what: via
        where:
          ref: sw_power
          shift: [0, sw_power_size_y]
        params.net: RAW
      via_pos_1: # left side of pwr switch
        what: via
        where:
          ref: sw_power
          shift: [0, -sw_power_size_y]
        params.net: pos
      via_pos_2: # pinky bottom left
        what: via
        where:
          ref: matrix_pinky_bot
          shift: [-kxo, -kyo]
        params.net: pos
      
      # JST Battery Connector
      jst_connector:
        what: jst_bat
        where.ref: jst
        params:
          reversible: true
          BAT_P: pos
          BAT_N: GND
      via_jst_pos: # adjacent to jst
        what: via
        where:
          ref: jst
          shift: [0, -jst_size_y]
        params.net: pos
      
      # M2 Screw Holes
      mount_left_top:
        what: mounting_hole
        where.ref: hole_left_top
      mount_left_bot:
        what: mounting_hole
        where.ref: hole_left_bot
      mount_right_top:
        what: mounting_hole
        where.ref: hole_right_top
      mount_right_bot:
        what: mounting_hole
        where.ref: hole_right_bot
      mount_btwn_thumb:
        what: mounting_hole
        where.ref: hole_btwn_thumb

#---------------------------------------
# sect: CASES
#---------------------------------------
# cases:
#   switchplate:
#     - what: outline
#       name: round_board_switch
#       extrude: 1.2
#   bottom:
#     - what: outline
#       name: round_board
#       extrude: 1.2
