points:
  key:
    padding: cy
    tags:
      1_u: true
  zones:
    matrix:
      rows:
        bottom:
        home:
        top:
      columns:
        pinky:
          key.spread: cx
          key.splay: 0
          key.origin: [0, -17]
          rows:
            bottom:
              name: pinky_bot
              bind: [0, 1, .5, 1.5]
            home:
              name: pinky_mid
              bind: [0, 1, 0, 1.5]
            top:
              name: pinky_top
              bind: [.5, 1, 0, 1.5]
        ring:
          key.spread: cx
          key.stagger: cx/2
          key.splay: 0
          key.origin: [0, -17]
          rows:
            bottom:
              name: ring_bot
              bind: [0, 0, 0, 0]
            home:
              name: ring_mid
              bind: [0, 0, 0, 0]
            top:
              name: ring_top
              bind: [.5, 1, 0, 1.25]
        middle:
          key.spread: cx
          key.stagger: cx/3
          key.splay: 0
          key.origin: [0, -17]
          rows:
            bottom:
              name: middle_bot
              bind: [0, 1, 0, 1]
            home:
              name: middle_mid
              bind: [0, 1, 0, 1]
            top:
              name: middle_top
              bind: [.5, 1.25, 0, 1.25]
        index:
          key.spread: cx
          key.stagger: -cx/3
          key.splay: 0
          key.origin: [0, -17]
          rows:
            bottom:
              name: index_bot
              bind: [0, 1, 0, 0]
            home:
              name: index_mid
              bind: [0, 0, 0, 0]
            top:
              name: index_top
              bind: [.5, 1.25, 0, 1]
        inner:
          key.spread: cx
          key.stagger: -cx/6
          key.splay: 0
          key.origin: [0, -17]
          rows:
            bottom:
              name: inner_bot
              bind: [0, 0, 0, 0]
            home:
              name: inner_mid
              bind: [5, 21.2, 12, 1]
              # add surface area for microcontroller
              # top: 5
              # right: 21.2
              # bottom: 12
              # left: 1
            top:
              name: inner_top
              bind: [0.25, 1.5, 0, 1]
              # add surface area for microcontroller
              # top: .25
              # right: 1.5
              # bottom: 0
              # left: 1
    thumbfan:
      anchor:
        ref: index_bot
        shift: [3, -21]
      rows:
        home:
      columns:
        inner:
          key.name: thumb_inner
          key.splay: -7.5
          key.bind: [10, 12, .5, 5.5]
          # connect key to matrix
          # top: 10
          # right: 12
          # bottom: 0.5
          # left: 5.5
          key.tags:
            15_u: true
        home:
          key.name: thumb_home
          key.spread: 1.25cx
          key.stagger:
          key.splay: -17.1
          key.origin: [-9, -9.5]
          key.bind: [18.5, 1.5, .5, 1]
          # connect key to microcontroller bottom
          # top: 18.5
          # right: 1.5
          # bottom: 0.5
          # left: 1

outlines:
  raw:
    - what: rectangle
      where: true
      bound: true
      size: [1cx - 0.5, 1cx -0.5]
  pinky_to_thumb:
    - what: rectangle
      size: [9, 19]
      adjust:
        ref: middle_bot
        rotate: 55
        shift: [1.5, -25]
    - what: rectangle
      size: [9, 10]
      adjust:
        ref: middle_bot
        rotate: 65
        shift: [1, -25.5]
    - what: rectangle
      size: [5, 20]
      adjust:
        ref: ring_bot
        rotate: 80
        shift: [5, -18]
    - what: rectangle
      size: [5, 50]
      adjust:
        ref: ring_bot
        rotate: 75
        shift: [10, -19]
    - what: rectangle
      size: [5, 30]
      adjust:
        ref: pinky_bot
        rotate: 85
        shift: [15, -8]
      # cover space under middle
      # and ring columns
    - what: rectangle
      size: [17, 40]
      adjust:
        ref: middle_bot
        rotate: 80
        shift: [-11, -13.5]
  round_index_top:
    - what: rectangle
      size: [18, 7]
      adjust:
        ref: index_top
        rotate: 0
        shift: [1.1, 5.9]
  cutout:
    - what: outline
      name: raw
      operation: add
      fillet: 2
    - what: outline
      name: pinky_to_thumb
      operation: add
      fillet: 2
    - what: outline
      name: round_index_top
      operation: add
      fillet: 2
  keycap_outlines:
    - what: rectangle
      where: "1_u"
      size: [1cx - 0.5, 1cy - 0.5]
      # Choc keycaps are 17.5 x 16.5
      bound: false
  keycap_outlines15:
    - what: rectangle
      where: "15_u"
      size: [1.5cx - 0.5, 1cy - 0.5]
      # Choc keycaps are 17.5 x 16.5
      bound: false
  preview: [keycap_outlines, keycap_outlines15]

pcbs:
  lazy_ferris:
    outlines:
      main:
        outline: cutout
      keycaps:
        outline: preview
        layer: Eco1.User
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{name}}"
          to: GND
      choc:
        what: choc
        where: true
        adjust:
          rotate: 180
        params:
          keycaps: true
          reverse: true
          from: "{{name}}"
          to: GND
      power_switch: # power switch
        what: pcm12
        where: true
        adjust:
          ref: thumb_home
          shift: [7.5, 15]
          rotate: 90
        params:
          reverse: true
          from: pos
          to: RAW
      reset_button: # reset button
        what: b3u1000p
        where: true
        adjust:
          ref: thumb_home
          shift: [7.5, 21.5]
          # keep 6.5 space between
          # power switch and reset button
          rotate: 0
        params:
          reverse: true
          r1: RST
          r2: GND
      pitch_connector_holes: # pitch connector holes
        what: bat
        where: true
        adjust:
          ref: inner_bot
          shift: [12, -6]
          rotate: 180
        params:
          neg: GND
      promicro: # microcontroller
        what: promicro_pretty
        where: true
        adjust:
          ref: inner_mid
          shift: [20.25, -4]
          rotate: -90
        params:
          orientation: down
          P2: pinky_top # Front
          P5: pinky_mid # Front
          P8: pinky_bot # Front
          P20: ring_top # Back
          P18: ring_mid # Back
          P14: ring_bot # Back
          P0: middle_top # Front
          P4: middle_mid # Front
          P7: middle_bot # Front
          P21: index_top # Back
          P19: index_mid # Back
          P15: index_bot # Back
          P1: inner_top # Front
          P3: inner_mid # Front
          P6: inner_bot # Front
          P9: thumb_inner # Front
          P10: thumb_home # Front
      puck:
        what: tenting_puck
        adjust:
          ref: middle_mid
          shift: [0, -8]
          rotate: 60
        params:
          # reverseSilks: false
          centerHole: false
          northHole: true
          westHole: true
          southHole: false
          eastHole: true
