points:
  key:
    padding: cy
    tags:
      is1u: true
  zones:
    matrix:
      rows:
        bottom:
        home:
        top:
      columns:
        pinky:
          key.spread: cx
          key.splay: 0
          key.origin: [0, -17]
          rows:
            bottom:
              name: pinky_bot
              bind: [0, 40, .5, 1.5]
              # 40 to right to connect
              # the bottom pinky to thumbfan
            home:
              name: pinky_mid
              bind: [0, 1, 0, 1.5]
            top:
              name: pinky_top
              bind: [.5, 1, 0, 1.5]
        ring:
          key.spread: cx
          key.stagger: cx/2
          key.splay: 0
          key.origin: [0, -17]
          rows:
            bottom:
              name: ring_bot
              bind: [0, 0, 0, 0]
            home:
              name: ring_mid
              bind: [0, 0, 0, 0]
            top:
              name: ring_top
              bind: [.5, 1, 0, 1]
        middle:
          key.spread: cx
          key.stagger: cx/3
          key.splay: 0
          key.origin: [0, -17]
          rows:
            bottom:
              name: middle_bot
              bind: [0, 1, 0, 1]
            home:
              name: middle_mid
              bind: [0, 1, 0, 1]
            top:
              name: middle_top
              bind: [.5, 1, 0, 1]
        index:
          key.spread: cx
          key.stagger: -cx/3
          key.splay: 0
          key.origin: [0, -17]
          rows:
            bottom:
              name: index_bot
              bind: [0, 1, 0, 0]
            home:
              name: index_mid
              bind: [0, 0, 0, 0]
            top:
              name: index_top
              bind: [.5, 1, 0, 1]
        inner:
          key.spread: cx
          key.stagger: -cx/6
          key.splay: 0
          key.origin: [0, -17]
          rows:
            bottom:
              name: inner_bot
              bind: [0, 0, 0, 0]
            home:
              name: inner_mid
              bind: [5, 21.2, 12, 1]
              # 5 for the microcontroller's top
              # 12 for the microcontroller's bottom
              # 21.2 for the microcontroller's width
            top:
              name: inner_top
              bind: [.5, 1.5, 0, 1]
    thumbfan:
      anchor:
        ref: index_bot
        shift: [3, -21]
      rows:
        home:
      columns:
        inner:
          key.name: thumb_inner
          key.splay: -7.5
          key.bind: [10, 12, .5, 5.5]
          key.tags:
            is15u: true
        home:
          key.name: thumb_home
          key.spread: 1.25cx
          key.stagger:
          key.splay: -15
          key.origin: [-9, -9.5]
          key.bind: [0, 1.5, .5, 0]

outlines:
  raw:
    - what: rectangle
      where: true
      bound: true
      size: [1cx - 0.5, 1cx -0.5]
    # rectangle outline between thumbfan
    # home and bottom of micro controller
    - what: rectangle
      size: [20.35, 31.5]
      adjust:
        ref: index_bot
        rotate: -28
        shift: [100, 100]
  cutout:
    - what: outline
      name: raw
      fillet: 2
  keycap_outlines:
    - what: rectangle
      where: "is1u"
      size: [1cx - 0.5, 1cy - 0.5]
      # Choc keycaps are 17.5 x 16.5
      bound: false
  keycap_outlines15:
    - what: rectangle
      where: "is15u"
      size: [1.5cx - 0.5, 1cy - 0.5]
      # Choc keycaps are 17.5 x 16.5
      bound: false
  preview: [keycap_outlines, keycap_outlines15]

pcbs:
  lazy_ferris:
    outlines:
      main:
        outline: cutout
      keycaps:
        outline: preview
        layer: Eco1.User
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{name}}"
          to: GND
      choc:
        what: choc
        where: true
        adjust:
          rotate: 180
        params:
          keycaps: true
          reverse: true
          from: "{{name}}"
          to: GND
      pcm12: # power switch
        what: pcm12
        where: true
        adjust:
          ref: thumb_home
          shift: [7, 15]
          rotate: 85
        params:
          reverse: true
          from: pos
          to: RAW
      reset_button: # reset button
        what: b3u1000p
        where: true
        adjust:
          ref: thumb_home
          shift: [7.5, 21.5]
          # keep 6.5 space between
          # power switch and reset button
          rotate: -5
        params:
          reverse: true
          r1: RST
          r2: GND
      bat: # pitch connector holes
        what: bat
        where: true
        adjust:
          ref: thumb_home
          shift: [-1, 11.5]
          rotate: 270
        params:
          neg: GND
      promicro: # microcontroller
        what: promicro_pretty
        where: true
        adjust:
          ref: inner_mid
          shift: [20.25, -4]
          rotate: -90
        params:
          orientation: down
          P2: pinky_top # Front
          P5: pinky_mid # Front
          P8: pinky_bot # Front
          P20: ring_top # Back
          P18: ring_mid # Back
          P14: ring_bot # Back
          P0: middle_top # Front
          P4: middle_mid # Front
          P7: middle_bot # Front
          P21: index_top # Back
          P19: index_mid # Back
          P15: index_bot # Back
          P1: inner_top # Front
          P3: inner_mid # Front
          P6: inner_bot # Front
          P9: thumb_inner # Front
          P10: thumb_home # Front
      # puck:
      #   what: tentingpuck
      #   adjust:
      #     ref: matrix_middle_home
      #     shift: [0, -8]
      #     rotate: 60
      #   params:
      #     reverseSilks: false
      #     centerHole: false
      #     northHole: true
      #     westHole: true
      #     southHole: false
      #     eastHole: true
