---
#--------------------------------------
# sect: ***UNITS***
#--------------------------------------
units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 4
  py: ky + 4
  # Double Padding Variables
  dpx: kx + 8
  dpy: ky + 8
  # Defaults to M2 Screws
  screw: 1.5
  standoff: 2.5
#--------------------------------------
# sect: ***POINTS***
#--------------------------------------
# columns nets up
points:
  zones:
    matrix:
      # Position in center of KiCAD workspace.
      anchor:
        shift: [100, -100]
      key:
        padding: ky
        spread: kx
      columns:
        pinky:
          key.column_net: P1
        ring:
          key:
            stagger: 2kx/3
            column_net: P0
        middle:
          key:
            stagger: kx/3
            column_net: P2
        index:
          key:
            stagger: -kx/3
            column_net: P3
        inner:
          key:
            stagger: -kx/6
            column_net: P4
      rows:
        bot:
          row_net: P19
        mid:
          row_net: P20
        top:
          row_net: P21
    thumb:
      anchor:
        ref: matrix_index_bot
        shift: [11, -25.25]
      columns:
        # Pinky side
        out:
          key:
            name: thumb_out
            splay: -15
            column_net: P14 # Back Side
        # Inner side
        in:
          key:
            name: thumb_in
            splay: -10
            spread: 1.32kx
            stagger: -kx/8
            column_net: P10 # Back Side
      rows:
        home:
          row_net: P16 # Back Side

#--------------------------------------
# sect: ***OUTLINES***
#--------------------------------------
outlines:
  # BOARD COMPONENTS
  _raw:
    - what: rectangle
      where: true
      bound: true
      size: [px, py]
  # Key outline minus .5mm to show overlapping keys.
  _keys:
    - what: rectangle
      where: true
      bound: false
      size: [kx-0.5,ky-0.5]
  
  # SHAPES
  board:
    - what: polygon
      operation: stack
      fillet: 3.5
      points:
        # Pinky - Bottom
        - ref: matrix_pinky_bot
          shift: [px, -.635px]
        - ref: matrix_pinky_bot
          shift: [.85px, -.615px]
        - ref: matrix_pinky_bot
          shift: [.75px, -.6px]
        - ref: matrix_pinky_bot
          shift: [.515px, -.57px]
        - ref: matrix_pinky_bot
          shift: [.2px, -.535px]
        - ref: matrix_pinky_bot
          shift: [0, -.525px]
        - ref: matrix_pinky_bot
          shift: [-.25px, -.51px]
        - ref: matrix_pinky_bot
          shift: [-.5px, -.5px]
        # Pinky - Top
        - ref: matrix_pinky_top
          shift: [-.5px, .445px]
        - ref: matrix_pinky_top
          shift: [-.485px, .505px]
        - ref: matrix_pinky_top
          shift: [-.47px, .542px]
        - ref: matrix_pinky_top
          shift: [-.44px, .585px]
        - ref: matrix_pinky_top
          shift: [-.4px, .623px]
        - ref: matrix_pinky_top
          shift: [-.3px, .695px]
        - ref: matrix_pinky_top
          shift: [-.1px, .81px]
        - ref: matrix_pinky_top
          shift: [0, .86px]
        # Ring
        - ref: matrix_ring_top
          shift: [-.7px, .37px]
        - ref: matrix_ring_top
          shift: [-.5px, .466px]
        - ref: matrix_ring_top
          shift: [-.4px, .508px]
        - ref: matrix_ring_top
          shift: [-.2px, .585px]
        - ref: matrix_ring_top
          shift: [0, .65px]
        - ref: matrix_ring_top
          shift: [.2px, .7px]
        # Middle
        - ref: matrix_middle_top
          shift: [-.5px, .45px]
        - ref: matrix_middle_top
          shift: [-.3px, .47px]
        - ref: matrix_middle_top
          shift: [-.1px, .478px]
        - ref: matrix_middle_top
          shift: [0, .483px]
        - ref: matrix_middle_top
          shift: [.1px, .478px]
        - ref: matrix_middle_top
          shift: [.3px, .47px]
        - ref: matrix_middle_top
          shift: [.5px, .45px]
        # Index
        - ref: matrix_index_top
          shift: [-.1px, .69px]
        - ref: matrix_index_top
          shift: [.1px, .66px]
        - ref: matrix_index_top
          shift: [.2px, .64px]
        - ref: matrix_index_top
          shift: [.3px, .62px]
        - ref: matrix_index_top
          shift: [.5px, .575px]
        # Inner
        - ref: matrix_inner_top
          shift: [-.3px, .707px]
        - ref: matrix_inner_top
          shift: [.2px, .58px]
        - ref: matrix_inner_top
          shift: [.37px, .525px]
        - ref: matrix_inner_top
          shift: [.4px, .512px]
        - ref: matrix_inner_top
          shift: [.44px, .486px]
        - ref: matrix_inner_top
          shift: [.46px, .465px]
        - ref: matrix_inner_top
          shift: [.47px, .45px]
        - ref: matrix_inner_top
          shift: [.485px, .41px]
        - ref: matrix_inner_top
          shift: [.495px, .37px]
        - ref: matrix_inner_top
          shift: [.5px, .3px]
        # nice!nano (mm): 34.1L x 18.3W x 3.3H
        # Top left mcu corner
        - ref: matrix_inner_top
          shift: [.5px, -.1px]
        # Top right mcu corner
        - ref: matrix_inner_top
          shift: [1.4px, -.1px]
        # Bottom right mcu corner
        - ref: matrix_inner_bot
          shift: [1.4px, -.75px]
        # Inner Thumb
        # MCU-thumb curve
        - ref: thumb_in
          shift: [.436px, .725px]
        - ref: thumb_in
          shift: [.447px, .7px]
        - ref: thumb_in
          shift: [.459px, .675px]
        - ref: thumb_in
          shift: [.47px, .65px]
        - ref: thumb_in
          shift: [.482px, .625px]
        - ref: thumb_in
          shift: [.495px, .595px]
        - ref: thumb_in
          shift: [.505px, .555px]
        - ref: thumb_in
          shift: [.51px, .515px]
        - ref: thumb_in
          shift: [.505px, 0]
        - ref: thumb_in
          shift: [.5px, -.5px]
        - ref: thumb_in
          shift: [-.5px, -.55px]
        # Outer Thumb
        - ref: thumb_out
          shift: [.45px, -.55px]
        - ref: thumb_out
          shift: [0, -.51px]
        - ref: thumb_out
          shift: [-.45px, -.48px]
        - ref: thumb_out
          shift: [-.75px, -.475px]
        - ref: thumb_out
          shift: [-px, -.48px]
  
  # COMBOS
  # Pure key outline with nice!nano MCU
  _raw_keys:
    - name: _raw
    - operation: stack
      name: _keys
  board_keys:
    - name: board
    - operation: subtract
      name: _keys
  board_raw_keys:
    - name: board
    - operation: subtract
      name: _raw_keys

#--------------------------------------
# sect: ***PCB***
#--------------------------------------
pcbs:
  snak:
    outlines:
      main:
        outline: board
      keycaps:
        outline: _keys
        layer: Eco1.User
    footprints:
      # MCU
      nice_nano:
        what: promicro_pretty
        where:
          ref: matrix_inner_mid
          shift: [20.25, -1.75]
          rotate: -90
        params:
          orientation: down
      # OLED
      nice_view:
        what: nice_view
        where:
          ref: matrix_inner_mid
          shift: [20.35, -6.5]
        params:
          side: F
          reverse: true
          jumpers_at_bottom: false
          MOSI: P5 # Front Side through via
          SCK: P6 # Front Side through via
          CS: P7 # Front Side through via
      via_oled_mosi: # Via for SCK Back
        what: via
        where:
          ref: matrix_inner_bot
          shift: [12.75, -1.75]
        params:
          net: P5
      via_oled_sck: # Via for SCK Back
        what: via
        where:
          ref: matrix_inner_bot
          shift: [14, -1]
        params:
          net: P6
      via_oled_cs: # Via for CS Back
        what: via
        where:
          ref: matrix_inner_bot
          shift: [15.25, -0.25]
        params:
          net: P7
      via_oled_gnd: # Via for GND Front
        what: via
        where:
          ref: matrix_inner_bot
          shift: [22.9, -1]
        params:
          net: GND
      # Key Switches and Diodes
      choc:
        what: choc_kim
        where: true
        params:
          show_keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      via_diode:
        what: via
        where: true
        params:
          net: "{{column_net}}"
        adjust:
          shift: [4, -2.75]
      # Power Switch
      power:
        what: switch_power
        where:
          ref: matrix_pinky_top
          shift: [-1, 15.75]
          rotate: 118
        params:
          reverse: true
          from: pos
          to: RAW
      jst_connector: # pitch connector holes
        what: jst_bat
        where:
          ref: matrix_inner_bot
          shift: [20.25, -11.75]
          rotate: 90
        params:
          reversible: true
          BAT_P: pos
          BAT_N: GND
      # Reset Button
      reset:
        what: b3u1000p
        where:
          ref: matrix_inner_bot
          shift: [15.5, -11.5]
          rotate: 90
        params:
          reverse: true
          r1: RST
          r2: GND
      via_raw_1: # right side of pwr switch
        what: via
        where:
          ref: matrix_pinky_top
          shift: [4, 18.75]
        params:
          net: RAW
      via_pos_1: # left side of pwr switch
        what: via
        where:
          ref: matrix_pinky_top
          shift: [-6, 12.75]
        params:
          net: pos
      via_pos_2:
        what: via
        where:
          ref: matrix_pinky_bot
          shift: [-9.25, -9.25]
        params:
          net: pos
      via_pos_3: # adjacent to reset 
        what: via
        where:
          ref: matrix_inner_bot
          shift: [12.25, -11.5]
        params:
          net: pos
      # Mounting Holes mounting_hole
      hole_left_top:
        what: mounting_hole
        where:
          ref: matrix_pinky_top
          shift: [9, 10.5]
      hole_left_bot:
        what: mounting_hole
        where:
          ref: matrix_pinky_bot
          shift: [9, 10.5]
      hole_right_top:
        what: mounting_hole
        where:
          ref: matrix_index_top
          shift: [8.5, -4]
      hole_right_bot:
        what: mounting_hole
        where:
          ref: matrix_index_bot
          shift: [8.5, -4]
      hole_btwn_thumb:
        what: mounting_hole
        where:
          ref: thumb_out
          shift: [12, 0]
      hole_left_thumb_in:
        what: mounting_hole
        where:
          ref: matrix_inner_bot
          shift: [12.5, -16.5]
      hole_right_thumb_in:
        what: mounting_hole
        where:
          ref: matrix_inner_bot
          shift: [27.75, -22.75]


#---------------------------------------
# sect: ***CASES***
#---------------------------------------
