---
#--------------------------------------
# sect: ***UNITS***
#--------------------------------------
units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 4
  py: ky + 4
  # Double Padding Variables
  dpx: kx + 8
  dpy: ky + 8
  # Defaults to M2 Screws
  screw: 1.5
  standoff: 2.5
#--------------------------------------
# sect: ***POINTS***
#--------------------------------------
# columns nets up
points:
  zones:
    matrix:
      # Position in center of KiCAD workspace.
      anchor:
        shift: [100, -100]
      key:
        padding: ky
        spread: kx
      columns:
        pinky:
          key.column_net: P1
        ring:
          key:
            stagger: 2kx/3
            column_net: P0
        middle:
          key:
            stagger: kx/3
            column_net: P2
        index:
          key:
            stagger: -kx/3
            column_net: P3
        inner:
          key:
            stagger: -kx/6
            column_net: P4
      rows:
        bot:
          row_net: P19
        mid:
          row_net: P20
        top:
          row_net: P21
    thumb:
      anchor:
        ref: matrix_index_bot
        shift: [11, -25]
      columns:
        # Pinky side
        out:
          key:
            name: thumb_out
            splay: -15
            column_net: P14 # Back Side
        # Inner side
        in:
          key:
            name: thumb_in
            splay: -10
            spread: 1.32kx
            stagger: -kx/8
            column_net: P10 # Back Side
      rows:
        home:
          row_net: P16 # Back Side

#--------------------------------------
# sect: ***OUTLINES***
#--------------------------------------
outlines:
  # PRIMARY COMPONENTS
  # Pure key outline.
  raw:
    - what: rectangle
      where: true
      bound: true
      size: [px, py]
  # nice!nano MCU (mm): 34.1L x 18.3W x 3.3H
  _mcu_rect:
    - what: rectangle
      where: true
      bound: true
      size: [15, 37]
      adjust:
        ref: matrix_inner_mid
        shift: [.5kx + 14.5, -.65kx]
  # Key outline minus .5mm to show overlapping keys.
  keys:
    - what: rectangle
      where: true
      bound: false
      size: [kx-0.5,ky-0.5]
  
  # BOARD SHAPES
  board:
    - what: polygon
      operation: stack
      fillet: 5
      points:
        - ref: matrix_pinky_top
          shift: [-.575px, .4px]
        - ref: matrix_ring_top
          shift: [-.5px, .5px]
        - ref: matrix_middle_top
          shift: [-.4px, .5px]
        - ref: matrix_middle_top
          shift: [.4px, .5px]
        - ref: matrix_inner_top
          shift: [.5px, .5px]
        # Top left mcu corner
        - ref: matrix_inner_top
          shift: [.5px, -.1px]
        # Top right mcu corner
        - ref: matrix_inner_top
          shift: [1.4px, -.1px]
        # Bottom right mcu corner
        - ref: matrix_inner_bot
          shift: [1.4px, -.75px]
        # MCU-thumb curve
        - ref: thumb_in
          shift: [.437px, .725px]
        - ref: thumb_in
          shift: [.448px, .7px]
        - ref: thumb_in
          shift: [.458px, .675px]
        - ref: thumb_in
          shift: [.467px, .65px]
        - ref: thumb_in
          shift: [.478px, .625px]
        - ref: thumb_in
          shift: [.49px, .6px]
        - ref: thumb_in
          shift: [.515px, .525px]
        # Top right thumb_in
        - ref: thumb_in
          shift: [.52px, .5px]
        - ref: thumb_in
          shift: [.55px, 0]
        # Bottom right thumb_in
        - ref: thumb_in
          shift: [.6px, -.85px]
        - ref: matrix_pinky_bot
          shift: [-.575px, -.55px]
  curve_top:
    - what: circle
      adjust:
        ref: matrix_middle_mid
        shift: [-8.5, -76.35]
      radius: 110
      operation: add
    - what: rectangle
      size: [5.32kx, 2px]
      adjust:
        ref: matrix_middle_top
        shift: [-.85, 5]
      operation: intersect
    - what: circle
      adjust:
        ref: matrix_middle_mid
        shift: [5, -61]
      radius: 90
      operation: intersect
  curve_bot:
    - what: circle
      adjust:
        ref: matrix_pinky_bot
        shift: [-8, -232.5]
      radius: 220
    - what: rectangle
      size: [5.7px, 3.25px]
      adjust:
        ref: matrix_middle_mid
        shift: [9, -60]
      operation: intersect
  _curve_bot_mcu:
    - what: rectangle
      size: [50, 50]
      adjust:
        ref: matrix_inner_bot
        shift: [54, -35]
        rotate: 65
    - what: circle
      adjust:
        ref: matrix_inner_bot
        shift: [-90, 14]
      radius: 125
      operation: add
  
  # OUTLINES
  # Pure key outline with nice!nano MCU
  board_raw:
    - name: board
    - operation: subtract
      name: raw
  board_keys:
    - name: board
    - operation: subtract
      name: keys
  board_raw_keys:
    - name: board_raw
    - operation: add
      name: keys
  round_board:
    - name: board
    - operation: add
      name: curve_top
    - operation: subtract
      name: curve_bot
      fillet: 5
  round_board_keys:
    - name: board
    - operation: add
      name: curve_top
    - operation: subtract
      name: curve_bot
      fillet: 5
    - operation: subtract
      name: keys

#--------------------------------------
# sect: ***PCB***
#--------------------------------------
pcbs:
  snak:
    outlines:
      main:
        outline: round_board
      keycaps:
        outline: keys
        layer: Eco1.User
    footprints:
      # MCU
      nice_nano:
        what: promicro_pretty
        where:
          ref: matrix_inner_mid
          shift: [20.25, -2]
          rotate: -90
        params:
          orientation: down
      # OLED
      nice_view:
        what: nice_view
        where:
          ref: matrix_inner_mid
          shift: [20.35, -6.5]
        params:
          side: F
          reverse: true
          jumpers_at_bottom: false
          MOSI: P5 # Front Side through via
          SCK: P6 # Front Side through via
          CS: P7 # Front Side through via
      via_oled_mosi: # Via for SCK
        what: via
        where:
          ref: matrix_inner_bot
          shift: [12.75, -2]
        params:
          net: P5
      via_oled_sck: # Via for SCK
        what: via
        where:
          ref: matrix_inner_bot
          shift: [14, -1.25]
        params:
          net: P6
      via_oled_cs: # Via for CS
        what: via
        where:
          ref: matrix_inner_bot
          shift: [15.25, -0.5]
        params:
          net: P7
      # Key Switches and Diodes
      choc:
        what: choc_kim
        where: true
        params:
          show_keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      via_diode:
        what: via
        where: true
        params:
          net: "{{column_net}}"
        adjust:
          shift: [4, -2.75]
      # Power Switch
      power:
        what: switch_power
        where:
          ref: matrix_pinky_top
          shift: [-1, 17]
          rotate: 120
        params:
          reverse: true
          from: pos
          to: RAW
      jst_connector: # pitch connector holes
        what: jst_bat
        where:
          ref: matrix_inner_bot
          shift: [20.25, -11.75]
          rotate: 90
        params:
          reversible: true
          BAT_P: pos
          BAT_N: GND
      # Reset Button
      reset:
        what: b3u1000p
        where:
          ref: matrix_inner_bot
          shift: [15.5, -11.5]
          rotate: 90
        params:
          reverse: true
          r1: RST
          r2: GND
      via_raw_1: # right side of pwr switch
        what: via
        where:
          ref: matrix_pinky_top
          shift: [4, 20]
        params:
          net: RAW
      via_pos_1: # left side of pwr switch
        what: via
        where:
          ref: matrix_pinky_top
          shift: [-6, 14]
        params:
          net: pos
      via_pos_2:
        what: via
        where:
          ref: matrix_pinky_bot
          shift: [-9.5, -9.5]
        params:
          net: pos
      via_pos_3:
        what: via
        where:
          ref: matrix_inner_bot
          shift: [12.25, -12.75]
        params:
          net: pos
      # Mounting Holes mounting_hole
      hole_left_top:
        what: mounting_hole
        where:
          ref: matrix_pinky_top
          shift: [9, 10.5]
      hole_left_bot:
        what: mounting_hole
        where:
          ref: matrix_pinky_bot
          shift: [9, 10.5]
      hole_right_top:
        what: mounting_hole
        where:
          ref: matrix_index_top
          shift: [8.25, -4]
      hole_right_bot:
        what: mounting_hole
        where:
          ref: matrix_index_bot
          shift: [-9, -3.5]
      hole_btwn_thumb:
        what: mounting_hole
        where:
          ref: thumb_out
          shift: [12, 0]
      hole_left_thumb_in:
        what: mounting_hole
        where:
          ref: matrix_inner_bot
          shift: [12.5, -16.5]
      hole_right_thumb_in:
        what: mounting_hole
        where:
          ref: matrix_inner_bot
          shift: [27, -22.5]


#---------------------------------------
# sect: ***CASES***
#---------------------------------------
