---
#--------------------------------------
# sect: ***UNITS***
#--------------------------------------
units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 4
  py: ky + 4
  # Double Padding Variables
  dpx: kx + 8
  dpy: ky + 8
  # Defaults to M2 Screws
  screw: 1
  standoff: 1.5
#--------------------------------------
# sect: ***POINTS***
#--------------------------------------
# columns nets up
points:
  zones:
    matrix:
      # Position in center of KiCAD workspace.
      anchor:
        shift: [100, -100]
      key:
        padding: ky
        spread: kx
      columns:
        pinky:
          key.column_net: P1
        ring:
          key:
            stagger: 2kx/3
            column_net: P0
        middle:
          key:
            stagger: kx/3
            column_net: P2
        index:
          key:
            stagger: -kx/3
            column_net: P3
        inner:
          key:
            stagger: -kx/6
            column_net: P4
      rows:
        bot:
          row_net: P14
        mid:
          row_net: P15
        top:
          row_net: P18
    thumb:
      anchor:
        ref: matrix_index_bot
        shift: [11, -25.25]
      columns:
        # Pinky side
        out:
          key:
            name: thumb_out
            splay: -15
            column_net: P16 # Back Side
        # Inner side
        in:
          key:
            name: thumb_in
            splay: -10
            spread: 1.32kx
            stagger: -kx/8
            column_net: P9 # Back Side
      rows:
        home:
          row_net: P10 # Back Side

#--------------------------------------
# sect: ***OUTLINES***
#--------------------------------------
outlines:
  # BOARD COMPONENTS
  _raw:
    - what: rectangle
      where: true
      bound: true
      size: [px, py]
  # Key outline minus .5mm to show overlapping keys.
  _keys:
    - what: rectangle
      where: true
      bound: false
      size: [kx-0.5,ky-0.5]
  _switches:
    - what: rectangle
      where: true
      bound: false
      size: 13.95
  
  # SHAPES
  _board:
    - what: polygon
      operation: stack
      points:
        # Pinky
        - ref: matrix_pinky_bot
          shift: [.2px, -.545px]
        - ref: matrix_pinky_bot
          shift: [-.2px, -.52px]
        - ref: matrix_pinky_bot
          shift: [-.51px, -.5px]
        - ref: matrix_pinky_top
          shift: [-.51px, .4px]
        # Ring
        - ref: matrix_ring_top
          shift: [-.4px, .45px]
        # Middle
        - ref: matrix_middle_top
          shift: [-.4px, .4px]
        - ref: matrix_middle_top
          shift: [.4px, .4px]
        # Inner
        - ref: matrix_inner_top
          shift: [.5px, .45px]
        # MCU (mm): 34.1L x 18.3W x 3.3H
        # Top left mcu corner
        - ref: matrix_inner_top
          shift: [.52px, -.075px]
        # Top right mcu corner
        - ref: matrix_inner_top
          shift: [1.357px, -.075px]
        # Bottom right mcu corner
        - ref: matrix_inner_bot
          shift: [1.357px, -.9px]
        # Thumb
        # MCU-thumb curve
        - ref: thumb_in
          shift: [.4px, .7px]
        - ref: thumb_in
          shift: [.46px, .56px]
        - ref: thumb_in
          shift: [.467px, .54px]
        - ref: thumb_in
          shift: [.475px, .52px]
        - ref: thumb_in
          shift: [.48px, .49px]
        - ref: thumb_in
          shift: [.505px, 0]
        - ref: thumb_in
          shift: [.5px, -.5px]
        - ref: thumb_in
          shift: [0, -.52px]

  _circle_top_right:
    - what: circle
      radius: 130
      adjust:
        ref: matrix_middle_mid
        shift: [-1, -102.65]
    - what: rectangle
      size: [2.815kx + 5, 1.2px]
      adjust:
        ref: matrix_index_top
        shift: [1.31, 4]
      operation: intersect
  _circle_top_left:
    - what: circle
      radius: 100
      adjust:
        ref: matrix_middle_mid
        shift: [12, -70.72]
    - what: rectangle
      size: [1.88kx + 5, 1.2px]
      adjust:
        ref: matrix_ring_top
        shift: [-9.78, 7]
      operation: intersect
  _curve_top:
    - name: _circle_top_left
    - name: _circle_top_right
  _curve_bot:
    - what: circle
      radius: 225
      adjust:
        ref: matrix_pinky_bot
        shift: [-11.5, -236.4]
    - what: rectangle
      size: [4.2px, 2px]
      adjust:
        ref: matrix_middle_mid
        shift: [7, -60]
      operation: intersect

  # Mounting Holes
  _holes_top:
    - what: circle
      radius: screw
      where:
        ref: matrix_pinky_top
        shift: [9, 10.5]
    - what: circle
      radius: screw
      where:
        ref: matrix_pinky_bot
        shift: [9, 10.5]
    - what: circle
      radius: screw
      where:
        ref: matrix_index_top
        shift: [9, -4]
    - what: circle
      radius: screw
      where:
        ref: matrix_index_bot
        shift: [9, -4]
    - what: circle
      radius: screw
      where:
        ref: thumb_out
        shift: [12, 0]
  _holes_bottom:
    - what: circle
      radius: standoff
      where:
        ref: matrix_pinky_top
        shift: [9, 10.5]
    - what: circle
      radius: standoff
      where:
        ref: matrix_pinky_bot
        shift: [9, 10.5]
    - what: circle
      radius: standoff
      where:
        ref: matrix_index_top
        shift: [9, -4]
    - what: circle
      radius: standoff
      where:
        ref: matrix_index_bot
        shift: [9, -4]
    - what: circle
      radius: standoff
      where:
        ref: thumb_out
        shift: [12, 0]

  # COMBOS
  # Pure key outline with nice!nano MCU
  _raw_keys:
    - name: _raw
    - operation: stack
      name: _keys
  top_plate:
    - name: _switches
    - operation: add
      name: _holes_top
  bottom_plate:
    - name: _holes_bottom
  board_keys:
    - name: _board
    - operation: subtract
      name: _keys
  board_raw_keys:
    - name: _board
    - operation: subtract
      name: _raw_keys
  round_board:
    - name: _board
      fillet: 4.35
    - operation: add
      name: _curve_top
    - operation: subtract
      name: _curve_bot
      fillet: 4
  round_board_keys:
    - name: round_board
    - operation: subtract
      name: _keys
  round_board_raw_keys:
    - name: round_board
    - operation: subtract
      name: _raw_keys

#--------------------------------------
# sect: ***PCB***
#--------------------------------------
pcbs:
  snak:
    outlines:
      main:
        outline: round_board
      plate_top:
        outline: top_plate
        layer: Eco1.User
      plate_bottom:
        outline: bottom_plate
        layer: Eco2.User
    footprints:
      # Key Switches and Diodes
      choc:
        what: choc_kim
        where: true
        params:
          show_keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      via_diode:
        what: via
        where: true
        params:
          net: "{{column_net}}"
        adjust:
          shift: [4, -2.75]
      
      # MCU
      nice_nano:
        what: nice_nano_pretty
        where:
          ref: matrix_inner_mid
          shift: [19.5, -0.5]
          rotate: 0
        params:
          traces: true
      # OLED
      nice_view:
        what: nice_view
        where:
          ref: matrix_inner_mid
          shift: [19.5, -6.5]
        params:
          reverse: true
          jumpers_at_bottom: false
          MOSI: P5 # Front Side through via
          SCK: P6 # Front Side through via
          CS: P7 # Front Side through via
      via_oled_mosi: # Via for SCK Back
        what: via
        where:
          ref: matrix_inner_bot
          shift: [12, -2.0]
        params:
          net: P5
      via_oled_sck: # Via for SCK Back
        what: via
        where:
          ref: matrix_inner_bot
          shift: [13.25, -1.25]
        params:
          net: P6
      via_oled_cs: # Via for CS Back
        what: via
        where:
          ref: matrix_inner_bot
          shift: [14.5, -0.5]
        params:
          net: P7
      via_oled_gnd: # Via for GND Front
        what: via
        where:
          ref: matrix_inner_bot
          shift: [28.5, -1.25]
        params:
          net: GND
      
      # Reset Button
      reset:
        what: switch_reset
        where:
          ref: matrix_inner_top
          shift: [-4.25, 13.25]
          rotate: 75
        params:
          reverse: true
          from: GND
          to: RST
      via_reset_rst: # left side of pwr switch
        what: via
        where:
          ref: matrix_inner_top
          shift: [-.75, 13.25]
        params:
          net: RST
      via_reset_gnd: # right side of pwr switch
        what: via
        where:
          ref: matrix_inner_top
          shift: [-1, 12.125]
        params:
          net: GND
      
      # Power Switch
      power:
        what: switch_power
        where:
          ref: matrix_pinky_top
          shift: [-1, 15.25]
          rotate: 120.75
        params:
          reverse: true
          from: pos
          to: RAW
      via_raw_1: # below reset button
        what: via
        where:
          ref: matrix_inner_top
          shift: [-1.25, 11]
        params:
          net: RAW
      via_raw_2: # right side of pwr switch
        what: via
        where:
          ref: matrix_pinky_top
          shift: [6, 19]
        params:
          net: RAW
      via_pos_1: # left side of pwr switch
        what: via
        where:
          ref: matrix_pinky_top
          shift: [-8, 11]
        params:
          net: pos
      via_pos_2:
        what: via
        where:
          ref: matrix_pinky_bot
          shift: [-9.25, -9.25]
        params:
          net: pos
      via_pos_3: # adjacent to jst 
        what: via
        where:
          ref: matrix_inner_bot
          shift: [16.5, -11.6]
        params:
          net: pos
      jst_connector: # pitch connector holes
        what: jst_bat
        where:
          ref: matrix_inner_bot
          shift: [25.25, -11.6]
          rotate: -90
        params:
          reversible: true
          BAT_P: pos
          BAT_N: GND
      # Mounting Holes mounting_hole
      hole_left_top:
        what: mounting_hole
        where:
          ref: matrix_pinky_top
          shift: [9, 10.5]
      hole_left_bot:
        what: mounting_hole
        where:
          ref: matrix_pinky_bot
          shift: [9, 10.5]
      hole_right_top:
        what: mounting_hole
        where:
          ref: matrix_index_top
          shift: [9, -4]
      hole_right_bot:
        what: mounting_hole
        where:
          ref: matrix_index_bot
          shift: [9, -4]
      hole_btwn_thumb:
        what: mounting_hole
        where:
          ref: thumb_out
          shift: [12, 0]
      # hole_left_thumb_in:
      #   what: mounting_hole
      #   where:
      #     ref: matrix_inner_bot
      #     shift: [12.5, -16.5]
      # hole_right_thumb_in:
      #   what: mounting_hole
      #   where:
      #     ref: matrix_inner_bot
      #     shift: [27.5, -22.5]


#---------------------------------------
# sect: ***CASES***
#---------------------------------------
# cases:
#   switchplate:
#     - what: outline
#       name: round_board_switch
#       extrude: 1.2
#   bottom:
#     - what: outline
#       name: round_board
#       extrude: 1.2