---
#--------------------------------------
# sect: ***UNITS***
#--------------------------------------
units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 4
  py: ky + 4
  # Double Padding Variables
  dpx: kx + 8
  dpy: ky + 8
  # Defaults to M2 Screws
  screw: 1.5
  standoff: 2.5
#--------------------------------------
# sect: ***POINTS***
#--------------------------------------
# columns nets up
points:
  zones:
    matrix:
      # Position in center of KiCAD workspace.
      anchor:
        shift: [100, -100]
      key:
        padding: ky
        spread: kx
      columns:
        pinky:
          key.column_net: P1
        ring:
          key:
            stagger: 2kx/3
            column_net: P0
        middle:
          key:
            stagger: kx/3
            column_net: P2
        index:
          key:
            stagger: -kx/3
            column_net: P3
        inner:
          key:
            stagger: -kx/6
            column_net: P4
      rows:
        bot:
          row_net: P19
        mid:
          row_net: P20
        top:
          row_net: P21
    thumb:
      anchor:
        ref: matrix_index_bot
        shift: [11, -25.25]
      columns:
        # Pinky side
        out:
          key:
            name: thumb_out
            splay: -15
            column_net: P3 # Back Side
        # Inner side
        in:
          key:
            name: thumb_in
            splay: -10
            spread: 1.32kx
            stagger: -kx/8
            column_net: P4 # Back Side
      rows:
        home:
          row_net: P18 # Back Side

#--------------------------------------
# sect: ***OUTLINES***
#--------------------------------------
outlines:
  # BOARD COMPONENTS
  _raw:
    - what: rectangle
      where: true
      bound: true
      size: [px, py]
  # Key outline minus .5mm to show overlapping keys.
  _keys:
    - what: rectangle
      where: true
      bound: false
      size: [kx-0.5,ky-0.5]
  _switches:
    - what: rectangle
      where: true
      bound: false
      size: [kx-0.5,ky-0.5]
  
  # SHAPES
  board:
    - what: polygon
      operation: stack
      points:
        # Pinky
        - ref: matrix_pinky_bot
          shift: [.2px, -.545px]
        - ref: matrix_pinky_bot
          shift: [-.2px, -.52px]
        - ref: matrix_pinky_bot
          shift: [-.51px, -.5px]
        - ref: matrix_pinky_top
          shift: [-.51px, .4px]
        # Ring
        - ref: matrix_ring_top
          shift: [-.5px, .4px]
        # Middle
        - ref: matrix_middle_top
          shift: [-.4px, .4px]
        - ref: matrix_middle_top
          shift: [.4px, .4px]
        # Inner
        - ref: matrix_inner_top
          shift: [.46px, .3px]
        # MCU (mm): 34.1L x 18.3W x 3.3H
        # Top left mcu corner
        - ref: matrix_inner_top
          shift: [.5px, -.1px]
        # Top right mcu corner
        - ref: matrix_inner_top
          shift: [1.357px, -.1px]
        # Bottom right mcu corner
        - ref: matrix_inner_bot
          shift: [1.357px, -.9px]
        # Thumb
        # MCU-thumb curve
        - ref: thumb_in
          shift: [.4px, .7px]
        - ref: thumb_in
          shift: [.46px, .56px]
        - ref: thumb_in
          shift: [.467px, .54px]
        - ref: thumb_in
          shift: [.475px, .52px]
        - ref: thumb_in
          shift: [.48px, .49px]
        - ref: thumb_in
          shift: [.505px, 0]
        - ref: thumb_in
          shift: [.5px, -.5px]
        - ref: thumb_in
          shift: [0, -.52px]

  _circle_top_right:
    - what: circle
      adjust:
        ref: matrix_middle_mid
        shift: [0, -107.2]
      radius: 135
    - what: rectangle
      size: [2.9kx + 5, 1.2px]
      adjust:
        ref: matrix_index_top
        shift: [0, 7]
      operation: intersect
  _circle_top_left:
    - what: circle
      adjust:
        ref: matrix_middle_mid
        shift: [9, -60.465]
      radius: 90
    - what: rectangle
      size: [1.76kx + 5, 1.2px]
      adjust:
        ref: matrix_ring_top
        shift: [-10.9, 7]
      operation: intersect
  _curve_top:
    - name: _circle_top_left
    - name: _circle_top_right
  _curve_bot:
    - what: circle
      adjust:
        ref: matrix_pinky_bot
        shift: [-11.5, -236.4]
      radius: 225
    - what: rectangle
      size: [4.2px, 2px]
      adjust:
        ref: matrix_middle_mid
        shift: [7, -60]
      operation: intersect

  # COMBOS
  # Pure key outline with nice!nano MCU
  _raw_keys:
    - name: _raw
    - operation: stack
      name: _keys
  board_keys:
    - name: board
    - operation: subtract
      name: _keys
  board_raw_keys:
    - name: board
    - operation: subtract
      name: _raw_keys
  round_board:
    - name: board
      fillet: 3.5
    - operation: add
      name: _curve_top
    - operation: subtract
      name: _curve_bot
      fillet: 4.5
  round_board_keys:
    - name: round_board
    - operation: subtract
      name: _keys
  round_board_raw_keys:
    - name: round_board
    - operation: subtract
      name: _raw_keys
  round_board_switch:
    - name: round_board
    - operation: subtract
      name: _switches

#--------------------------------------
# sect: ***PCB***
#--------------------------------------
pcbs:
  snak:
    outlines:
      main:
        outline: round_board
      keycaps:
        outline: _keys
        layer: Eco1.User
    footprints:
      # MCU
      nice_nano:
        what: nice_nano_pretty
        where:
          ref: matrix_inner_mid
          shift: [20.05, -0.5]
          rotate: 0
        params:
          traces: true
          P1_label: Col1
          P0_label: Col2
          P2_label: Col3
          P3_label: Col4
          P4_label: Col5
          P5_label: MOSI
          P6_label: SCK
          P7_label: CS
          P18_label: Row1
          P19_label: Row2
          P20_label: Row3
          P21_label: Row4
      # OLED
      nice_view:
        what: nice_view
        where:
          ref: matrix_inner_mid
          shift: [20.1, -6.75]
        params:
          reverse: true
          jumpers_at_bottom: false
          MOSI: P5 # Front Side through via
          SCK: P6 # Front Side through via
          CS: P7 # Front Side through via
      via_oled_mosi: # Via for SCK Back
        what: via
        where:
          ref: matrix_inner_bot
          shift: [12.5, -2.0]
        params:
          net: P5
      via_oled_sck: # Via for SCK Back
        what: via
        where:
          ref: matrix_inner_bot
          shift: [13.75, -1.25]
        params:
          net: P6
      via_oled_cs: # Via for CS Back
        what: via
        where:
          ref: matrix_inner_bot
          shift: [15, -0.5]
        params:
          net: P7
      via_oled_gnd: # Via for GND Front
        what: via
        where:
          ref: matrix_inner_bot
          shift: [22.65, -1.25]
        params:
          net: GND
      # Key Switches and Diodes
      choc:
        what: choc_kim
        where: true
        params:
          show_keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      via_diode:
        what: via
        where: true
        params:
          net: "{{column_net}}"
        adjust:
          shift: [4, -2.75]
      # Reset Button
      reset:
        what: switch_reset
        where:
          ref: matrix_inner_top
          shift: [0, 13.25]
          rotate: 75
        params:
          reverse: true
          from: GND
          to: RST
      via_reset_gnd: # right side of pwr switch
        what: via
        where:
          ref: matrix_inner_top
          shift: [3.75, 12.25]
        params:
          net: GND
      via_reset_rst: # left side of pwr switch
        what: via
        where:
          ref: matrix_inner_top
          shift: [-3.75, 14.25]
        params:
          net: RST
      # Power Switch
      power:
        what: switch_power
        where:
          ref: matrix_pinky_top
          shift: [-1, 15.5]
          rotate: 121.75
        params:
          reverse: true
          from: pos
          to: RAW
      via_raw_1: # right side of pwr switch
        what: via
        where:
          ref: matrix_pinky_top
          shift: [4, 19]
        params:
          net: RAW
      via_pos_1: # left side of pwr switch
        what: via
        where:
          ref: matrix_pinky_top
          shift: [-6, 13]
        params:
          net: pos
      via_pos_2:
        what: via
        where:
          ref: matrix_pinky_bot
          shift: [-9.25, -9.25]
        params:
          net: pos
      via_pos_3: # adjacent to jst 
        what: via
        where:
          ref: matrix_inner_bot
          shift: [16.5, -11.75]
        params:
          net: pos
      via_pos_4: # adjacent to jst 
        what: via
        where:
          ref: matrix_inner_bot
          shift: [7, -11.75]
        params:
          net: pos
      jst_connector: # pitch connector holes
        what: jst_bat
        where:
          ref: matrix_inner_bot
          shift: [25.25, -11.75]
          rotate: -90
        params:
          reversible: true
          BAT_P: pos
          BAT_N: GND
      # Mounting Holes mounting_hole
      hole_left_top:
        what: mounting_hole
        where:
          ref: matrix_pinky_top
          shift: [9, 10.5]
      hole_left_bot:
        what: mounting_hole
        where:
          ref: matrix_pinky_bot
          shift: [9, 10.5]
      hole_right_top:
        what: mounting_hole
        where:
          ref: matrix_index_top
          shift: [8.5, -4]
      hole_right_bot:
        what: mounting_hole
        where:
          ref: matrix_index_bot
          shift: [8.5, -4]
      hole_btwn_thumb:
        what: mounting_hole
        where:
          ref: thumb_out
          shift: [12, 0]
      hole_left_thumb_in:
        what: mounting_hole
        where:
          ref: matrix_inner_bot
          shift: [12.5, -16.5]
      hole_right_thumb_in:
        what: mounting_hole
        where:
          ref: matrix_inner_bot
          shift: [27.5, -22.5]


#---------------------------------------
# sect: ***CASES***
#---------------------------------------
cases:
  switchplate:
    - what: outline
      name: round_board_switch
      extrude: 1.2
  bottom:
    - what: outline
      name: round_board
      extrude: 1.2
