#--------------------------------------
# sect: META
#--------------------------------------
meta:
  engine: 4.0.4
  version: 1.2.1
  author: JackMatanky
  name: snak
  ref: &kb_ref "SNAK v1.2.1"
  full_name: &kb_full_name "SNAK: Sisyphus Needed a Keyboard, v1.2.1"
  url: &kb_url https://github.com/JackMatanky/kb_snak
  # switch:
  #   $extends: presets.mx
  #   $extends: presets.choc_v1
  #   $extends: presets.choc_v2

#--------------------------------------
# sect: UNITS
#--------------------------------------
units:
  # Key Size (Choc V1)
  # Space Between Key Centers
  kx: cx # 18
  ky: cy # 17
  kxo: 0.5(kx)
  kyo: 0.5(ky)
  # Column Spread and Row Padding
  spread_key: 18.5
  padding_key: 17.5
  # Keycap Size
  keycap_x: 17.5
  keycap_y: 16.5
  # Switch Plate Key Cutout
  kcutout_x: 13.9
  kcutout_y: 13.9

  # Padding Variables
  px: kx + 4
  py: ky + 4
  pxo: 0.5(px)
  pyo: 0.5(py)

  # Double Padding Variables
  dpx: kx + 8
  dpy: ky + 8

  # Column Stagger
  stagger_ring: 5(kx)/8
  stagger_middle: (kx)/3
  stagger_index: -2(kx)/5
  stagger_inner: -4(kx)/7
  stagger_thumb: -(kx)/10

  # Thumb
  offset_thumb_x: 15
  offset_thumb_y: -25
  splay_thumb_out: -17
  splay_thumb_in: -10
  spread_thumb_in: kx + 2.25

  # XIAO nRF52840: 20 x 17.5 x 3.3 (mm)
  mcu_size_x: 17.5
  mcu_size_y: 20
  mcu_size_xo: 0.5(mcu_size_x)
  mcu_size_yo: 0.5(mcu_size_y)
  mcu_spacing_left: 1.5
  mcu_spacing_right: 0.75
  mcu_shift_x: kxo + mcu_size_xo + mcu_spacing_left
  mcu_shift_y: kyo - mcu_size_yo - 1.5
  mcu_right_board_shift_x: mcu_size_xo + mcu_spacing_right
  mcu_top_left_board_shift_x: mcu_spacing_left - mcu_size_xo - 4
  mcu_top_board_shift_y: mcu_size_yo + 1.25
  mcu_bottom_board_shift_y: -(mcu_size_yo)

  # nice!view: 36 x 14 x 2.9 (mm)
  oled_size_x: 14
  oled_size_y: 36
  oled_size_xo: 0.5(oled_size_x)
  oled_size_yo: 0.5(oled_size_y)
  oled_jumper_y: 2.6
  oled_shift_x: 0
  oled_shift_y: mcu_size_yo - (oled_size_yo - 1)


  # Screen Size and Offset From Center
  oled_screen_offset_x: 1.6
  oled_screen_offset_top_y: 2.45 + 3.65 # = 6.1
  oled_screen_offset_bot_y: 1.3 + 1.7 + 1.6 # = 4.6
  oled_screen_size_x: oled_size_x - 2(oled_screen_offset_x)
  oled_screen_size_y: oled_size_y - (oled_screen_offset_top_y + oled_screen_offset_bot_y)
  oled_screen_size_xo: 0.5(oled_screen_size_x)
  oled_screen_size_yo: 0.5(oled_screen_size_y)
  oled_screen_shift_x: 0
  oled_screen_shift_y: oled_size_yo - (oled_screen_size_yo + oled_screen_offset_top_y)

  # Power Switch
  sw_power_size_x: 4.55 # Footprint; Actual width: 3.0 ± 0.05
  sw_power_size_y: 8.8 # Footprint; Actual height: 8.3
  sw_power_size_xo: 0.5(sw_power_size_x)
  sw_power_size_yo: 0.5(sw_power_size_y)
  sw_power_shift_x: 0
  sw_power_shift_y: mcu_size_yo - 0.6 # + sw_power_size_xo
  sw_power_rotate: 90

  # JST Battery Connector (2P, Curved Needed)
  # Footprint center at (3.45, 1.85)
  jst_size_x: 6.9 # Footprint; Actual width: 4.5 ± 0.2
  jst_size_y: 10.35 # Footprint; Actual height: 6.1 ± 0.1
  jst_size_xo: 0.5(jst_size_x)
  jst_size_yo: 0.5(jst_size_y)
  jst_main_size_y: 3.7
  jst_main_size_yo: 0.5(jst_main_size_y)
  jst_sec_size_y: jst_size_y - jst_main_size_y
  jst_sec_size_yo: 0.5(jst_sec_size_y)
  jst_main_shift_x: (oled_size_xo - jst_main_size_yo) + 1.5
  jst_main_shift_y: -(oled_size_yo + jst_size_xo + 1)
  jst_sec_shift_x: 0
  jst_sec_shift_y: -(jst_main_size_yo + jst_sec_size_yo)
  jst_rotate: 270

  # Reset Switch
  sw_reset_size_x: 3.4 # Footprint; Actual width: 2.9
  sw_reset_size_y: 5.5 # Footprint; Actual height: 4.7
  sw_reset_size_xo: 0.5(sw_reset_size_x)
  sw_reset_size_yo: 0.5(sw_reset_size_y)
  sw_reset_shift_x: -.15(kx)
  sw_reset_shift_y: .74(ky)
  sw_reset_rotate: 128

  # PCB and Case Holes
  # Points height and width
  hole_size_x: 0.1
  hole_size_y: 0.1
  # Screw and Standoff Radii
  screw: 1
  standoff: 1.5
  # Positions
  hole_right_shift_x: 9
  hole_right_shift_y: -6.25
  hole_left_shift_x: 9
  hole_left_shift_y: 7.5
  hole_thumb_shift_x: .5(spread_thumb_in)
  hole_thumb_shift_y: 0

  # Outline Shapes
  board_fillet: 3.5
  round_board_fillet: 3.5

  # Top Border
  top_rect_size_x: 5(kx) + 0.4(pxo)
  top_rect_size_y: 1.5px
  top_rect_shift_x: -0.25
  top_rect_shift_y: 0
  
  # Top Right Circle
  top_right_crcl_radius: 67.5
  top_right_crcl_shift_x: 1
  top_right_crcl_shift_y: -39.5

  # Top Left Circle
  top_left_crcl_radius: 100
  top_left_crcl_shift_x: 15
  top_left_crcl_shift_y: -68

  # Bottom Curve
  bot_rect_size_x: 5.25(px)
  bot_rect_size_y: 2(px)
  bot_rect_shift_x: 7
  bot_rect_shift_y: -60

  bot_circle_radius: 235
  bot_circle_shift_x: -11.5
  bot_circle_shift_y: -270

#--------------------------------------
# sect: POINTS
#--------------------------------------
# columns nets up
points.zones:
  # * Base Keyboard Layout
  matrix:
    # Position in center of KiCAD workspace.
    anchor.shift: [100, -100]
    key:
      padding: padding_key
      spread: spread_key
    rows:
      bot.row_net: R3
      mid.row_net: R2
      top.row_net: R1
    columns:
      pinky:
        key.tags: pinky
        rows:
          bot.skip: true
          mid.column_net: C1
          top.column_net: C1
      ring:
        key:
          tags: ring
          stagger: stagger_ring
        rows:
          bot.column_net: C1
          mid.column_net: C2
          top.column_net: C2
      middle:
        key:
          tags: middle
          stagger: stagger_middle
        rows:
          bot.column_net: C2
          mid.column_net: C3
          top.column_net: C3
      index:
        key:
          tags: index
          stagger: stagger_index
        rows:
          bot.column_net: C3
          mid.column_net: C4
          top.column_net: C4
      inner:
        key:
          tags: inner
          stagger: stagger_inner
        rows:
          bot.skip: true
          mid.column_net: C5
          top.column_net: C5
  thumb:
    key.tags: thumb
    anchor:
      ref: matrix_index_bot
      shift: [offset_thumb_x, offset_thumb_y]
    rows.home.row_net: R3
    columns:
      # Pinky side
      out.key:
        name: thumb_out
        splay: splay_thumb_out
        column_net: C4
      # Inner side
      in.key:
        name: thumb_in
        stagger: stagger_thumb
        spread: spread_thumb_in
        splay: splay_thumb_in
        column_net: C5
  
  # * Components
  mcu:
    key:
      tags: part
      name: mcu
      width: mcu_size_x
      height: mcu_size_y
    anchor:
      ref: matrix_inner_top
      shift: [mcu_shift_x, mcu_shift_y - .4(kx)]
  oled:
    key:
      tags: part
      name: oled
      width: oled_size_x
      height: oled_size_y
    anchor:
      ref: mcu
      shift: [oled_shift_x, oled_shift_y]
  oled_screen:
    key:
      tags: part
      name: oled_screen
      width: oled_screen_size_x
      height: oled_screen_size_y
    anchor:
      ref: oled
      shift: [oled_screen_shift_x, oled_screen_shift_y]
  sw_power:
    key:
      tags: part
      name: sw_power
      width: sw_power_size_x
      height: sw_power_size_y
    anchor:
      ref: mcu
      shift: [sw_power_shift_x, sw_power_shift_y]
      rotate: sw_power_rotate
  jst_main:
    key:
      tags: part
      name: jst_main
      width: jst_size_x
      height: jst_main_size_y
    anchor:
      ref: oled
      shift: [jst_main_shift_x, jst_main_shift_y]
      rotate: jst_rotate
  jst_sec:
    key:
      tags: part
      name: jst_sec
      width: jst_size_x
      height: jst_sec_size_y
    anchor:
      ref: jst_main
      shift: [jst_sec_shift_x, jst_sec_shift_y]
      #rotate: jst_rotate
  sw_reset:
    key:
      tags: part
      name: sw_reset
      width: sw_reset_size_x
      height: sw_reset_size_y
    anchor:
      ref: matrix_pinky_top
      shift: [sw_reset_shift_x, sw_reset_shift_y]
      rotate: sw_reset_rotate

  # * Mounting Holes
  hole_left_top:
    key:
      tags: hole
      width: hole_size_x
      height: hole_size_y
    anchor:
      ref: matrix_pinky_top
      shift: [hole_left_shift_x, hole_left_shift_y]
  hole_left_bot:
    key:
      tags: hole
      width: hole_size_x
      height: hole_size_y
    anchor:
      ref: matrix_pinky_bot
      shift: [hole_left_shift_x, hole_left_shift_y]
  hole_right_top:
    key:
      tags: hole
      width: hole_size_x
      height: hole_size_y
    anchor:
      ref: matrix_index_top
      shift: [hole_right_shift_x, hole_right_shift_y]
  hole_right_bot:
    key:
      tags: hole
      width: hole_size_x
      height: hole_size_y
    anchor:
      ref: matrix_index_bot
      shift: [hole_right_shift_x, hole_right_shift_y]
  hole_btwn_thumb:
    key:
      tags: hole
      width: hole_size_x
      height: hole_size_y
    anchor:
      ref: thumb_out
      shift: [hole_thumb_shift_x, hole_thumb_shift_y]

#--------------------------------------
# sect: OUTLINES
#--------------------------------------
outlines:
  # BOARD COMPONENTS
  _raw:
    - what: rectangle
      where: /(matrix|thumb)_/
      bound: true
      size: [px, py]
  _keycaps:
  # Key outline minus .5mm to show overlapping keys.
    - what: rectangle
      where: /(matrix|thumb)_/
      bound: false
      size: [keycap_x, keycap_y]
  _switches:
    - what: rectangle
      where: /(matrix|thumb)_/
      bound: false
      size: [kcutout_x, kcutout_y]
  
  _mcu:
    - what: rectangle
      size: [mcu_size_x, mcu_size_y]
      adjust.ref: mcu
  _oled:
    - what: rectangle
      size: [oled_size_x, oled_size_y]
      adjust.ref: oled
  _oled_screen:
    - what: rectangle
      size: [oled_screen_size_x, oled_screen_size_y]
      adjust.ref: oled_screen
  _sw_power:
    - what: rectangle
      size: [sw_power_size_x, sw_power_size_y]
      adjust.ref: sw_power
  _jst:
    - what: rectangle
      size: [jst_size_x, jst_main_size_y]
      adjust.ref: jst_main
    - what: rectangle
      size: [jst_size_x, jst_sec_size_y]
      adjust.ref: jst_sec
  _sw_reset:
    - what: rectangle
      size: [sw_reset_size_x, sw_reset_size_y]
      adjust.ref: sw_reset
  _holes_screw:
    - what: circle
      where: [hole]
      radius: screw
  _holes_standoff:
    - what: circle
      where: [hole]
      radius: standoff

  # SHAPES
  _board:
    - what: polygon
      fillet: board_fillet
      points:
        # Pinky
        - ref: matrix_pinky_mid
          shift: [-.95pxo, -pyo]
        - ref: matrix_pinky_top
          shift: [-.95pxo, .5kyo]
        # Ring
        - ref: matrix_ring_top
          shift: [-kxo, kyo]
        # Middle
        - ref: matrix_middle_top
          shift: [-kxo, kyo]
        - ref: matrix_middle_top
          shift: [kxo, kyo]
        # Inner
        - ref: matrix_inner_top
          shift: [.25(kx), .5(pyo)]
        # MCU
        - ref: mcu # MCU Top Left Corner
          shift: [mcu_top_left_board_shift_x, mcu_top_board_shift_y]
        - ref: mcu # MCU Top Right Corner
          shift: [mcu_right_board_shift_x, mcu_top_board_shift_y]
        # Thumb
        # MCU-thumb curve
        - ref: thumb_in
          shift: [pxo, .9(pyo)]
        - ref: thumb_in
          shift: [pxo, -pyo]

  # Top Border
  # Right Side
  _top_rect:
    - what: rectangle
      size: [top_rect_size_x, top_rect_size_y]
      adjust:
        ref: matrix_middle_top
        shift: [top_rect_shift_x, top_rect_shift_y]
  _top_curve:
    - name: _top_rect
    - what: circle
      radius: top_right_crcl_radius
      adjust:
        ref: matrix_middle_mid
        shift: [top_right_crcl_shift_x, top_right_crcl_shift_y]
      operation: intersect
  
  # Bottom Border
  _bot_rect:
    - what: rectangle
      size: [bot_rect_size_x, bot_rect_size_y]
      adjust:
        ref: matrix_middle_mid
        shift: [bot_rect_shift_x, bot_rect_shift_y]
  _bot_curve:
    - name: _bot_rect
    - what: circle
      radius: bot_circle_radius
      adjust:
        ref: matrix_pinky_mid
        shift: [bot_circle_shift_x, bot_circle_shift_y]
      operation: intersect

  # DXF PREVIEWS
  # Pure key outline with nice!nano MCU
  _raw_keys:
    - name: _raw
    - operation: stack
      name: _keycaps
  _components:
    - name: _mcu
      operation: stack
    - name: _oled
      operation: stack
    - name: _oled_screen
      operation: stack
    - name: _sw_power
      operation: stack
    - name: _jst
      operation: stack
    - name: _sw_reset
      operation: stack

  plate_top:
    - name: _holes_screw
    - name: _switches
    - name: _oled_screen
  plate_bottom:
    - name: _holes_standoff
    - name: _mcu
    - name: _jst
  plate_opening:
    - name: _sw_power
    - name: _sw_reset
  board_keys:
    - name: _board
    - operation: subtract
      name: _keycaps
  board_raw_keys:
    - name: _board
    - operation: subtract
      name: _raw_keys
  round_board:
    - name: _board
    - operation: add
      name: _top_curve
    - operation: subtract
      name: _bot_curve
      fillet: round_board_fillet
  _round_board_keys:
    - name: round_board
    - operation: subtract
      name: _keycaps
  round_board_raw_keys:
    - name: round_board
    - operation: subtract
      name: _raw_keys
  round_board_mcu_keys:
    - name: _round_board_keys
    - operation: subtract
      name: _mcu
  round_board_full:
    - name: _round_board_keys
    - operation: stack
      name: _components

#--------------------------------------
# sect: PCB
#--------------------------------------
pcbs.snak:
  outlines:
    main.outline: round_board
    plate_top:
      outline: plate_top
      layer: Eco1.User
    plate_bottom:
      outline: plate_bottom
      layer: Eco2.User
  footprints:
    # Key Switches and Diodes
    choc:
      what: choc_kim
      where: /(matrix|thumb)_/
      params:
        reverse: true
        hotswap: true
        solder: false
        show_keycaps: true
        from: "{{column_net}}"
        to: "{{colrow}}"
    diode:
      what: diode_kim
      where: /(matrix|thumb)_/
      adjust.shift: [0, -5]
      params:
        include_tht: true
        from: "{{colrow}}"
        to: "{{row_net}}"
    via_col_row_high:
      what: via
      where: /(matrix|thumb)_/
      adjust.shift: [-4.0, 1.5]
      params.net: "{{colrow}}"
    via_matrix_row_net:
      what: via
      where: [top, mid]
      adjust.shift: [-6.0, -5.0]
      params.net: "{{row_net}}"
    via_matrix_col_net_high:
      what: via
      where: /matrix_*/
      adjust.shift: [0, 3.0]
      params.net: "{{column_net}}"
    via_matrix_col_net_low:
      what: via
      where: /_(rows_top|rows_mid)/
      adjust.shift: [-5.25, -2.5]
      params.net: "{{column_net}}"
    via_thumb_row_net:
      what: via
      where:
        ref: thumb_out
        shift: [10.5, -6.5]
      params.net: R4
    via_thumb_col_net:
      what: via
      where: /thumb_*/
      adjust.shift: [0, 8.5]
      params.net: "{{column_net}}"

    # MCU
    nice_nano:
      what: nice_nano_pretty
      where.ref: mcu
      params:
        traces: true
        show_via_labels: true
        show_silk_labels: true
        show_instructions: true

        # Pin Assignments (Controller on top facing down)
        # Right Side
        P0: "F1"  # FREE PIN
        P1: "F2"  # FREE PIN
        # GND
        # GND
        P2: "F3"  # FREE PIN
        P3: "DPD" # MOSI: Display Data
        P4: "DPC" # SCK: Display Clock
        P5: "DPE" # Display CS (nice!view only)
        P6: "R1"  # Row Top
        P7: "R2"  # Row Middle
        P8: "R3"  # Row Bottom
        P9: "R4"  # Row Thumb

        # Left Side
        # RAW     # Battery Pos
        # GND     # Ground / Battery Neg
        # RST     # Reset pin
        # VCC     # External Power
        P21: "C1" # Column Pinky
        P20: "C2" # Column Ring
        P19: "C3" # Column Middle
        P18: "C4" # Column Index
        P15: "C5" # Column Inner
        P14: "F4"  # FREE PIN
        P16: "F5" # Thumb Outer
        P10: "F6" # Thumb Inner
    # OLED
    nice_view:
      what: nice_view
      where.ref: oled
      params:
        reverse: true
        MOSI: DPD
        SCK: DPC
        CS: DPE
        show_labels: true
        jumpers_at_bottom: true
    via_oled_mosi:
      what: via
      where:
        ref: mcu
        shift: [-(mcu_size_xo - 2.4), -(mcu_size_yo + 1.65)]
      params.net: DPD
    via_oled_sck:
      what: via
      where:
        ref: mcu
        shift: [-(mcu_size_xo - 1.6), -(mcu_size_yo + 0.9)]
      params.net: DPC
    via_oled_cs:
      what: via
      where:
        ref: mcu
        shift: [-(mcu_size_xo - 0.8), -(mcu_size_yo + 0.15)]
      params.net: DPE
    via_oled_GND:
      what: via
      where:
        ref: mcu
        shift: [0, -(mcu_size_yo + 4.85)]
      params.net: GND

    # Power Switch
    power:
      what: switch_power
      where.ref: sw_power
      params:
        reverse: true
        from: pos
        to: RAW
    # via_raw: # right side of pwr switch
    #   what: via
    #   where:
    #     ref: sw_power
    #     shift: [-(sw_power_size_xo - 0.25), sw_power_size_yo - 1.1]
    #     # shift: [0, sw_power_size_y]
    #   params.net: RAW
    via_pos: # left side of pwr switch
      what: via
      where:
        ref: sw_power
        shift: [0.5(sw_power_size_xo), 0]
      params.net: pos
    
    # JST Battery Connector
    jst_connector:
      what: jst_bat
      where.ref: jst_main
      params:
        reversible: true
        BAT_P: pos
        BAT_N: GND
    via_jst_pos: # adjacent to jst
      what: via
      where:
        ref: jst_main
        shift: [0, -(jst_size_yo - 1.25)]
      params.net: pos
    via_jst_gnd: # adjacent to jst
      what: via
      where:
        ref: jst_main
        shift: [0, jst_main_size_yo + 0.5]
      params.net: GND
    
    # Reset Button
    reset:
      what: switch_reset
      where.ref: sw_reset
      params:
        reverse: true
        from: GND
        to: RST
    via_rst_1: # left side
      what: via
      where:
        ref: sw_reset
        shift: [0.35(sw_reset_size_xo), -(sw_reset_size_yo + 1)]
      params.net: RST
    via_rst_2: # left side
      what: via
      where:
        ref: sw_reset
        shift: [-0.35(sw_reset_size_xo), -(sw_reset_size_yo + 3)]
      params.net: RST
    via_reset_gnd_1: # right side
      what: via
      where:
        ref: sw_reset
        shift: [-0.35(sw_reset_size_xo), -(sw_reset_size_yo + 1)]
      params.net: GND
    via_reset_gnd_2: # right side
      what: via
      where:
        ref: sw_reset
        shift: [0.35(sw_reset_size_xo), -(sw_reset_size_yo + 3)]
      params.net: GND
    
    # M2 Screw Holes
    holes_mount:
      what: mounting_hole
      where: [hole]

#---------------------------------------
# sect: CASES
#---------------------------------------
# cases:
#   switchplate:
#     - what: outline
#       name: round_board_switch
#       extrude: 1.2
#   bottom:
#     - what: outline
#       name: round_board
#       extrude: 1.2
