points:
  key:
    padding: cy
    spread: cx
    splay: 0
    tags:
      1_u: true
  zones:
    matrix:
      rows:
        bottom:
        home:
        top:
      columns:
        pinky:
          key.origin: [0, -17]
          rows:
            bottom:
              name: pnk_bot
              column_net: P8 # Front
              bind: [0, 30, .75, 1.5]
            home:
              name: pnk_hom
              column_net: P5 # Front
              bind: [0, 1, 0, 1.5]
            top:
              name: pnk_top
              column_net: P2 # Front
              bind: [.5, 1, 0, 1.5]
        ring:
          key.stagger: 2cx/3
          key.origin: [0, -17]
          rows:
            bottom:
              name: rng_bot
              column_net: P14 # Back
              bind: [0, 0, 0, 0]
            home:
              name: rng_hom
              column_net: P18 # Back
              bind: [0, 0, 0, 0]
            top:
              name: rng_top
              column_net: P20 # Back
              bind: [.5, 1, 0, 1.25]
        middle:
          key.stagger: cx/3
          key.origin: [0, -17]
          rows:
            bottom:
              name: mid_bot
              column_net: P7 # Front
              bind: [0, 1, 18, 1]
              # 18 to cover space next
              # to inner thumb key
            home:
              name: mid_hom
              column_net: P4 # Front
              bind: [0, 1, 0, 1]
            top:
              name: mid_top
              column_net: P0 # Front
              bind: [.5, 1.25, 0, 1.25]
        index:
          key.stagger: -cx/3
          key.origin: [0, -17]
          rows:
            bottom:
              name: ind_bot
              column_net: P15 # Back
              bind: [0, 1, 12, 0]
              # 12 to cover space next
              # to inner thumb key
            home:
              name: ind_hom
              column_net: P19 # Back
              bind: [0, 0, 0, 0]
            top:
              name: ind_top
              column_net: P21 # Back
              bind: [.5, 1.25, 0, 1]
        inner:
          key.stagger: -cx/6
          key.origin: [0, -17]
          rows:
            bottom:
              name: inn_bot
              column_net: P6 # Front
              bind: [0, 21.1, 6.25, 0]
            home:
              name: inn_hom
              column_net: P3 # Front
              bind: [5.25, 21.1, 12.5, 1]
              # surface area for microcontroller
              # top: 5.25
              # right: 21.1
              # bottom: 12.5
              # left: 1
            top:
              name: inn_top
              column_net: P1 # Front
              bind: [.5, 1.5, 0, 1]
              # add surface area for microcontroller
              # top: 1
              # right: 1.5
              # bottom: 0
              # left: 1
    thumbfan:
      anchor:
        ref: ind_bot
        shift: [8.5, -23]
      rows:
        home:
      columns:
        inner:
          key.name: thm_inr
          key.splay: -5
          key.column_net: P9 # Front
          key.bind: [10, 12, .75, 6]
          # connect key to matrix
          # top: 10
          # right: 12
          # bottom: 0.75
          # left: 6
          key.tags:
            15_u: true
        home:
          key.name: thm_hom
          key.spread: 1.4cx
          key.stagger: -.15cx
          key.splay: -15
          key.column_net: P10 # Front
          key.bind: [1.5, 1.5, 1, 2]
          # connect key to microcontroller bottom
          # top: 1.5
          # right: 1.5
          # bottom: 1
          # left: 2

outlines:
  raw:
    - what: rectangle
      where: true
      bound: true
      size: [1cx - 0.5, 1cx -0.5]
  thumb_to_pinky:
    - what: rectangle
      # closest to thumb
      size: [17, 10]
      adjust:
        ref: mid_bot
        rotate: 161
        shift: [8.5, -30.9]
      fillet: 4
    - what: rectangle
      size: [10, 8]
      adjust:
        ref: mid_bot
        rotate: 162
        shift: [2.5, -30]
      fillet: 3
    - what: rectangle
      size: [8, 7]
      adjust:
        ref: rng_bot
        rotate: 163
        shift: [16.5, -23.3]
      fillet: 3
    - what: rectangle
      size: [9, 6]
      adjust:
        ref: rng_bot
        rotate: 168
        shift: [10.75, -22.47]
      fillet: 3
    - what: rectangle
      size: [15, 5]
      adjust:
        ref: rng_bot
        rotate: 172
        shift: [2.5, -21.7]
    - what: rectangle
      size: [17, 5]
      adjust:
        ref: pnk_bot
        rotate: 173.5
        shift: [5, -7.75]
  round_thumb_bot:
    - what: rectangle
      size: [8.5, 4]
      adjust:
        ref: thm_hom
        rotate: 10
        shift: [-11, -8.4]
    - what: rectangle
      size: [10, 4]
      adjust:
        ref: thm_hom
        rotate: 2
        shift: [-5, -7.9]
    - what: rectangle
      size: [7, 4]
      adjust:
        ref: thm_hom
        rotate: 11.5
        shift: [-15, -9.19]
  round_thumb_pmicro:
    - what: rectangle
      size: [9.5, 12]
      adjust:
        ref: thm_hom
        rotate: 25
        shift: [6.5, 11.25]
      fillet: 9
    - what: rectangle
      size: [6, 6]
      adjust:
        ref: thm_hom
        rotate: -1
        shift: [7.3, 9.4]

  cutout:
    - what: outline
      name: raw
      operation: add
      fillet: 1.25
    - what: outline
      name: thumb_to_pinky
      operation: add
      fillet: 2
    - what: outline
      name: round_thumb_bot
      operation: add
      fillet: 2
    - what: outline
      name: round_thumb_pmicro
      operation: add
      fillet: 2

  keycap_1u:
    - what: rectangle
      where: "1_u"
      size: [1cx - 0.5, 1cy - 0.5]
      # Choc keycaps are 17.5 x 16.5
      bound: false
  keycap_15u:
    - what: rectangle
      where: "15_u"
      size: [1.5cx - 0.5, 1cy - 0.5]
      # Choc keycaps are 17.5 x 16.5
      bound: false
  keycaps:
    - what: outline
      name: keycap_1u
      operation: add
    - what: outline
      name: keycap_15u
      operation: add

  preview:
    - what: outline
      name: keycaps
      operation: stack
    - what: outline
      name: cutout
      operation: stack

pcbs:
  lazy_ferris:
    outlines:
      main:
        outline: cutout
      keycaps:
        outline: keycaps
        layer: Eco1.User
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: GND
      choc:
        what: choc
        where: true
        adjust:
          rotate: 180
        params:
          keycaps: true
          reverse: true
          from: "{{column_net}}"
          to: GND
      microcontroller: # promicro microcontroller
        what: promicro_pretty
        where:
          ref: inn_hom
          shift: [20.25, -3.75]
          rotate: -90
        params:
          orientation: down
      power_switch: # power switch
        what: pcm12
        where:
          ref: inn_bot
          shift: [27.25, -8]
          rotate: 90
        params:
          reverse: true
          from: pos
          to: RAW
      reset_button: # reset button
        what: b3u1000p
        where:
          ref: inn_bot
          shift: [26.75, -15]
          # keep 6.5 space between
          # power switch and reset button
          rotate: -20
        params:
          reverse: true
          r1: RST
          r2: GND
      pitch_connector_holes: # pitch connector holes
        what: bat
        where:
          ref: inn_bot
          shift: [12.5, -6]
          rotate: 0
        params:
          neg: GND
      # puck:
      #   what: tenting_puck
      #   adjust:
      #     ref: mid_hom
      #     shift: [0, -8]
      #     rotate: 60
      #   params:
      #     reverseSilks: false
      #     centerHole: false
      #     northHole: true
      #     westHole: true
      #     southHole: false
      #     eastHole: true
